[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/VWeqlhYJWFL-keIvesuXr26hhGAcfX3Q"

[env]
PRIVATE_KEY = {env="PRIVATE_KEY"}
BASE_SEPOLIA_RPC_URL = {env="BASE_SEPOLIA_RPC_URL"}